--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/angga7togk/PowerEssentials
build-by-default: true
branches:
- main
- Add-Command-Mute
projects:
  PowerEssentials:
    path: ""
    icon: "icon.png"
...
