--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/angga7togk/PowerEssentials
build-by-default: true
branches:
- main
projects:
  PowerEssentials:
    path: ""
  icon:
    path: "img/flower.png"
...
