name: PowerEssentials
main: angga7togk\poweressentials\PowerEssentials
api: 5.0.0
version: 1.0.0
author: Angga7Togk

permissions:
  poweressentials.setlobby:
    default: op
  poweressentials.lobby:
    default: true
  poweressentials.fly:
    default: op
  poweressentials.fly.other:
    default: op
  poweressentials.antinamespace.bypass:
    default: op
  poweressentials.gamemode.gmc:
    default: op
  poweressentials.gamemode.gms:
    default: op
  poweressentials.gamemode.gma:
    default: op
  poweressentials.gamemode.gmspc:
    default: op
  poweressentials.gamemode.other:
    default: op
  poweressentials.gmc:
    default: op
  poweressentials.gms:
    default: op
  poweressentials.gma:
    default: op
  poweressentials.gmspc:
    default: op
  poweressentials.nickname:
    default: op
  poweressentials.nickname.other:
    default: op
  poweressentials.home:
    default: true
  poweressentials.sethome:
    default: true
  poweressentials.delhome:
    default: true
  poweressentials.coordinates:
    default: true
  poweressentials.warp:
    default: true
  poweressentials.addwarp:
    default: op
  poweressentials.delwarp:
    default: op
  poweressentials.heal:
    default: op
  poweressentials.heal.other:
    default: op
  poweressentials.feed:
    default: op
  poweressentials.feed.other:
    default: op
  poweressentials.sudo:
    default: op
  poweressentials.banitem:
    default: op
  poweressentials.banitem.bypass:
    default: op
  poweressentials.worldprotect:
    default: op
  poweressentials.worldprotect.bypass:
    default: op
  poweressentials.vanish:
    default: op
  poweressentials.vanish.other:
    default: op
  poweressentials.vanish.see:
    default: op
  poweressentials.randomteleport:
    default: true
  poweressentials.size:
    default: op
  poweressentials.afk:
    default: true
  poweressentials.afk.bypass:
    default: op
  poweressentials.onesleep.cancel:
    default: true
  poweressentials.tpa:
    default: true
  poweressentials.tpall:
    default: op
  poweressentials.itemid:
    default: op
  poweressentials.repair:
    default: op
  poweressentials.repair.all:
    default: op
  poweressentials.repair.other:
    default: op
  poweressentials.senditem:
    default: true
  poweressentials.getpos:
    default: op
