##################################
#         PowerEssentials        #
##################################

# config version
# !!!dont change this!!!!
config-version: 1.0

# language
language: en_us

# on join force set gamemode
gamemode-join-enable: true
gamemode-join: SURVIVAL

# on join force spawn to lobby position
spawn-lobby-join: true

# Players with space names are prohibited from entering
anti-namespace: false

# show vanilla coordinates
# when show-coordinates is false, command /coordinates for player will not work
show-coordinates: true

##################################
#            Nicknames           #
##################################
# maximum number of characters
nickname-max-char: 15

# blacklist nickname
# This feature only works for /nickname
blacklist-nicknames:
- admin
- owner
- staff

##################################
#            Commands            #
##################################
# commands option disable and enabled
# List: lobby, fly, gamemode, nickname, home, coordinates, warp
disable-commands:
- command1

##################################
#               HOME             #
##################################
# blacklist set home in world
home-world-blacklists:
- world_nether
- world_the_end

# Permission Limit
# if you enable this feature, you can limit the number of homes per player
home-permission-limit: false
home-permission-default-limit: 3

home-permission-limits:
  homelimit.5: 5
  homelimit.10: 10

##################################
#         RANDOM TELEPORT        #
##################################

# random teleport anti water
# if you set this to true, the teleport will not be on water
random-teleport-anti-water: true
random-teleport-timeout: 3

# random teleport range
# if you set the range to 0, the teleport will be on the same location
random-teleport-range:
  x: [ -1000, 1000 ] # -1000 to 1000
  z: [ -1000, 1000 ] # -1000 to 1000

random-teleport-world-blacklists:
- nether
- world_nether
- the_end
- end
- world_the_end
- world_end


##################################
#         PLAYER SIZE            #
##################################

size-max: 5.0


##################################
#            ONE SLEEP           #
##################################

one-sleep-enable: true

# if you enable this feature, other player can vote to cancel sleep player
cancel-sleep-vote: true
cancel-sleep-vote-count: 3 # need 3 votes to cancel sleep player
cancel-sleep-vote-timeout: 15 # 15 seconds to vote




