##################################
#         PowerEssentials        #
##################################
# You can customize your own languages via the languages folder, just create it
language: en_US

# on join force set gamemode
gamemode-join-enable: true
gamemode-join: SURVIVAL

# on join force spawn to lobby position
spawn-lobby-join: true

# Players with space names are prohibited from entering
anti-namespace: false

##################################
#            Nicknames           #
##################################
# maximum number of characters
nickname-max-char: 15

# blacklist nickname
# This feature only works for /nickname
blacklist-nicknames:
  - admin
  - owner
  - staff

##################################
#            Commands            #
##################################
# commands option disable and enabled
# leave the command inside the list if you
# want to keep the command registered
commands:
  - "lobby"
  - "setlobby"
  - "fly"
  - "gmc"
  - "gms"
  - "gma"
  - "gmspc"
  - "nickname"
