name: PHPStan Analysis

on:
  push:
  pull_request:

jobs:
  phpstan:
    name: Run PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@2.32.0
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --ignore-platform-req=* --no-progress --no-suggest --prefer-dist

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=1G
